// Company policies; preserved sections with clarified company status and planning targets.
export const restoredPoliciesEn: Record<string, { title: string; description: string; sections: { title: string; text: string }[] }> = {
  "cookie-policy": {
    "title": "Cookie Policy",
    "description": "How we use cookies and how to control them in accordance with GDPR and international laws",
    "sections": [
      {
        "title": "Cookie Policy",
        "text": "Company establishment date: June 29, 2026 | Version: 2.0\n\nFOR RELIEF LTD (“the Foundation”) uses cookies and similar tracking technologies on its website. This policy details what cookies are, what types they are, how we use them, and how you can control them.\n\nThis policy complies with the following international regulations:\n• European General Data Protection Regulation (GDPR) — Article 5 et seq\n• European ePrivacy Directive 2002/58/EC amended in 2009\n• British Data Protection Regulation (UK GDPR / PECR 2003)\n• Turkish Data Protection Law (KVKK) and Law No. 5651\n• Digital privacy laws in Arab and Asian countries"
      },
      {
        "title": "What are cookies?",
        "text": "Cookies are small text files that are saved on your device (computer, phone, tablet) when you visit our website. They contain information such as your session ID or preferences, and are sent to our servers upon each visit.\n\nWhy are cookies used?\n• Remember your preferences and settings across different visits\n• Ensuring that the website operates properly and securely\n• Analyze how visitors use the site and improve their experience\n• Provide content relevant to your interests\n• Measure the effectiveness of our marketing campaigns\n\nSimilar technologies we use:\n• Web Beacons: Small transparent images used to measure interaction with emails\n• Local Storage: Store data locally on your device (such as donation basket content)\n• Session Storage: To store temporary data during a browsing session\n• Fingerprinting: We do not use this privacy-invasive technology"
      },
      {
        "title": "Types of cookies we use",
        "text": "First - Strictly Necessary Cookies:\nThese cookies are essential for the website to function and operate properly, and cannot be disabled without affecting the basic functionality of the website. It does not require your prior consent.\n\nExamples and uses:\n┌──────────────────────────────── ─────────────────────────────────┐\n│ Name │ Purpose │ Duration │\n├────────────────┼──────────────── ──────────────┼──────────────────┤\n│ session_id │ Manage your browsing session │ Single session │\n│ csrf_token │ Protection from CSRF attacks │ Single session │\n│ cart_data │ Save donation cart content │ 7 days │\n│ lang_pref │ Remember selected language preference │ 1 year │\n│ cookie_consent │ Remember your consent to cookies │ 1 year │\n└──────────────────────────────── ─────────────────────────────────┘\n\nSecond - Performance and analysis cookies:\nThey help us understand how visitors use the site, which enables us to improve performance. It collects anonymous or semi-anonymous data.\n\n┌──────────────────────────────── ─────────────────────────────────┐\n│ Provider │ Cookies │ Purpose │\n├───────────────────┼──────────── ─────────┼──────────────────────┤\n│ Google Analytics │ _ga, _gid, _gat │ Visitor statistics │\n│ Google Analytics │ _ga_XXXXXXXX │ Session Highlights │\n└──────────────────────────────── ─────────────────────────────────┘\nNote: We enable IP masking in Google Analytics to protect your privacy.\nDuration: up to 26 months.\n\nThird - Functional Cookies:\nThey are used to remember your choices and preferences, such as your chosen language or preferred donation amounts.\n\n┌──────────────────────────────── ─────────────────────────────────┐\n│ Name │ Purpose │ Duration │\n├──────────────────┼────────────── ─────────────────┼───────────────┤\n│ user_prefs │ Interface preferences │ 30 days │\n│ last_campaign │ Last campaign viewed │ 7 days │\n└──────────────────────────────── ─────────────────────────────────┘\n\nFourth - Payment Gateway Cookies:\nUsed by Stripe and PayPal to ensure the security of your financial transactions. Subject to the privacy policies of these independent companies.\n\n┌──────────────────────────────── ─────────────────────────────────┐\n│ Provider │ Cookies │ Purpose │\n├────────────┼─────────────────── ──────┼─────────────────────────┤\n│ Stripe │ __stripe_mid, __stripe_sid │ Payment Security │\n│ PayPal │ tsrce, x-pp-s, PYPF │ PayPal Secure Session │\n└──────────────────────────────── ─────────────────────────────────┘"
      },
      {
        "title": "How to control cookies?",
        "text": "You have full control over cookies. Here are the available methods:\n\n1. Browser settings:\nYou can disable or delete cookies from your browser settings. Note: Disabling necessary cookies may affect some site functionality.\n\n• Google Chrome:\n  Settings → Privacy and security → Cookies and other site data\n\n• Mozilla Firefox:\n  Options → Privacy and security → Cookies and site data\n\n• Safari (Mac):\n  Preferences → Privacy → Manage site data\n\n• Safari (iPhone/iPad):\n  Settings → Safari → Privacy & Security\n\n• Microsoft Edge:\n  Settings → Cookies and site permissions\n\n• Samsung Internet (Android):\n  Settings → Privacy and security → Cookies\n\n2. Stop tracking by Google Analytics:\nYou can install the official browser extension from Google:\n👉 tools.google.com/dlpage/gaoptout\nOr the “Do Not Track” setting in your browser.\n\n3. Tools for selective rejection of ads:\n• Your Online Choices (Europe): youronlinechoices.eu\n• Network Advertising Initiative (US): optout.networkadvertising.org\n• Digital Advertising Alliance: optout.aboutads.info\n\n4. Mobile devices:\n• iOS: Settings → Privacy & Security → Tracking → Turn off “Allow apps to request tracking”\n• Android: Settings → Privacy → Ads → Reset Advertising Identifier"
      },
      {
        "title": "Cookies and your legal rights",
        "text": "According to international regulations:\n\nEuropean Union and Britain:\n• You have the right to view the cookies we use and reject unnecessary ones.\n• We obtain your explicit consent before placing any non-essential cookies.\n• You can withdraw your consent at any time through your browser settings.\n• You have the right to lodge a complaint with the ICO (UK) or your local supervisory authority (EU).\n\nTürkiye:\n• According to KVKK, non-essential cookies require explicit consent.\n• You can object to the use of tracking cookies by rejecting them when the consent notice appears.\n\nArab and Asian countries:\n• According to the data protection principles applicable in each country, you have the right to refuse analytical cookies.\n• We respect the “Do Not Track” (DNT) setting that you can enable in your browser.\n\nWhat happens if I reject cookies?\n• Necessary cookies: They cannot be rejected — they are essential for the site to function.\n• Analytical cookies: can be rejected without any impact on basic site functionality.\n• Payment cookies: Rejecting them may prevent a donation from completing — Stripe and PayPal need them for security."
      },
      {
        "title": "Updates to this policy",
        "text": "We review our Cookie Policy regularly to ensure it is compatible with the latest technologies and applicable laws. Company establishment date: June 29, 2026.\n\nHow do we notify you of updates?\n• We display a prominent notice on the site when any material changes are made.\n• We send an email notification to our newsletter subscribers.\n• We maintain a historical record of previous releases which you can request from us.\n\nYour continued use of the site after any updates are posted constitutes acceptance of the new policy.\n\nTo contact us regarding cookies or privacy:\nEmail: info@forrelief.org\nResponse within: 72 working hours"
      },
      {
        "title": "Questions about cookies?",
        "text": "Our Privacy Team is ready to answer your questions"
      }
    ]
  },
  "aml-policy": {
    "title": "Anti-fraud and money laundering",
    "description": "Our procedures to combat money laundering, fraud and terrorist financing are in accordance with international FATF standards",
    "sections": [
      {
        "title": "Anti-money laundering, fraud and terrorist financing policy",
        "text": "Company establishment date: June 29, 2026 | Version: 2.0\n\nFOR RELIEF LTD is committed to the highest standards of financial integrity and combating financial crime. This policy sets out the comprehensive framework for preventing money laundering (AML), countering the financing of terrorism (CFT), fraud detection and reporting.\n\nInternational frameworks to which this policy complies:\n• The 40 international recommendations of the Financial Action Task Force (FATF).\n• Fifth European Anti-Money Laundering Directive (5AMLD — 2018/843/EU)\n• Sixth European Anti-Money Laundering Directive (6AMLD — 2018/1673/EU)\n• British Anti-Money Laundering Act (POCA 2002 and Money Laundering Regulations 2017)\n• Turkish Anti-Money Laundering Law No. 5549/2006\n• Arab Regulations for Combating Money Laundering (MENAFATF)\n• Wolfsberg Principles for non-profit organizations"
      },
      {
        "title": "Definition of money laundering and terrorist financing",
        "text": "Money Laundering:\nThe process of legitimizing money earned from illegal activities by introducing it into the formal financial system. It usually goes through three stages:\n\n1. Placement stage: introducing illicit funds into the financial system.\n2. Layering: Conducting multiple transactions to hide the true origin of the funds.\n3. Integration stage: returning funds to the formal economy in the form of legitimate funds.\n\nTerrorist Financing:\nProviding or collecting funds - whether legitimate or illegitimate - with the intention of using them to finance terrorist activities or terrorist organizations.\n\nWhy does this matter to the donation sector?\nThe non-profit sector is at risk of being exploited for money laundering or terrorist financing due to:\n• The large volume of transactions and their geographical spread\n• Charitable character that may be exploited to lend legitimacy\n• Difficulty verifying the identity of donors in some cases"
      },
      {
        "title": "Know Your Customer (KYC) procedures",
        "text": "We implement the “Know Your Customer — KYC” policy according to the risk levels:\n\nLevel 1 — Basic Verification (for regular donations):\n• Payment data validation (via Stripe/PayPal).\n• Verify that the donor’s name is not on international sanctions lists.\n• Monitor transaction patterns to detect anomalies.\n\nLevel 2 — Medium Verification (for large donations):\nApplies to donations above a certain threshold (determined internally):\n• Require full name and verifiable email.\n• Review the history of the donor’s transactions with the platform.\n• Verify the source of funds if necessary.\n\nLevel 3 - Enhanced Due Diligence - EDD:\nApplied in high-risk cases:\n• Very large donations from unknown people.\n• Donations from countries on the FATF high-risk lists.\n• Unexplained donation patterns (such as repeated donations in amounts below the mandatory reporting threshold).\n• Donors from the category of “Politically Exposed Persons” (PEPs - Politically Exposed Persons).\n\nIn these cases we may ask:\n• A copy of an official identity document.\n• A statement of the source of funds.\n• Clarifying the purpose of the donation.\n• Stop the transaction pending verification."
      },
      {
        "title": "Transaction monitoring procedures",
        "text": "We adopt a multi-layered monitoring system to detect suspicious transactions:\n\n1. Real-time Screening:\nEvery transaction goes instantly through:\n• Check the US OFAC sanctions list\n• Examination of European sanctions lists (EU Consolidated List)\n• Examination of the United Nations Sanctions List.\n• Examination of the UK Sanctions List.\n• Examination of applicable regional terrorism lists\n\n2. Red Flags we monitor:\n• Donate small amounts repeatedly at very short intervals (Smurfing)\n• Using credit cards with different names or addresses for the same user\n• Request a refund of part of the donation through a different payment method\n• Donations of IP addresses in countries subject to comprehensive international sanctions\n• Payment modes that test the limits of the card processing system (Card Testing).\n• Donations accompanied by a request to influence the direction of funds to a specific party\n\n3. Periodic manual review:\n• Weekly review of unusual transactions by the financial officer\n• Monthly audit of donation patterns to detect long-term anomalies\n• Quarterly assessment of AML risks and updating detection mechanisms"
      },
      {
        "title": "Rejecting transactions and freezing funds",
        "text": "When do we decline the transaction?\nWe will reject any transaction immediately and without prior notice if:\n• The donor’s name matches an approved international sanctions list.\n• A stolen or reported fraudulent credit card was used.\n• The transaction was from an IP in a country with a comprehensive ban that prevents transactions.\n• The payment gateway (Stripe/PayPal) rejected the transaction for security reasons.\n• The donor was found to be using a fake identity or hacked data.\n• There have been strong indicators indicating intent to launder money.\n\nWhat happens after rejection?\n• The donor is notified in a general message (without revealing the reason for the security rejection).\n• Records of declined transactions are kept for 5 years.\n• The competent authorities will be notified if the matter exceeds the limits of reasonable suspicion.\n\nFreezing funds:\nIn cases that require investigation:\n• Funds are temporarily frozen until the verification process is completed.\n• Priority is given to cases involving high risks.\n• The funds will be recovered if their legality is proven, or they will be referred to the competent authorities if the opposite is proven."
      },
      {
        "title": "Suspicious Transaction Reporting (STR)",
        "text": "Our reporting obligations:\nWe are committed to submitting suspicious transaction reports (STR) to the competent authorities in accordance with applicable laws:\n\n• In the European Union: for local Financial Intelligence Units (FIUs).\n• In the United Kingdom: to the National Crime Agency (NCA) via the UKFIU system\n• In Türkiye: Finance Unit (MASAK)\n• In Arab countries: to the relevant regulatory authorities (such as the Financial Information Processing Unit in the Emirates)\n\nWhat prevents us from disclosing:\nAccording to the law, we are prohibited from informing suspects that their transactions are under investigation or that they have been reported (Tipping Off). This ban is mandatory and protects us legally.\n\nRecords and documentation:\nWe keep all records related to precautionary measures and suspicious reports for a period of at least 5 years in accordance with FATF requirements."
      },
      {
        "title": "Responsibility for compliance and training program",
        "text": "Compliance Officer (MLRO):\nThe organization appoints a Compliance Officer (Money Laundering Reporting Officer — MLRO) responsible for:\n• Supervising the implementation of the AML/CFT policy\n• Regularly review and update compliance procedures\n• Receiving internal reports of suspicious transactions\n• Preparing STR reports and sending them to the competent authorities\n• Communicating with regulatory and supervisory authorities\n\nStaff training:\n• All employees receive mandatory AML/CFT training upon hire\n• Annual update training on the latest money laundering methods and identifying them\n• Periodic tests to ensure understanding of procedures\n• A documented training record for each employee\n\nRisk assessment:\nWe conduct a comprehensive risk assessment at least once a year, or when significant changes occur in the organization's operations, and update our procedures based on the assessment results."
      },
      {
        "title": "Report fraud",
        "text": "If you discover or suspect any fraudulent activity:\nEmail: info@forrelief.org\nWe respond within: 24 hours on business days\n\nWhat is considered fraud that we require you to report?\n• Using the organization’s name or logo to collect unauthorized donations\n• Claims to be associated with the organization for incorrect purposes\n• Using other donors’ data to make fake donations\n• Any activity that suggests the organization is being exploited for illegal purposes\n\nWe guarantee:\n• Deal with all reports confidentially\n• Whistleblower Protection in accordance with applicable laws\n• Investigate every report seriously and objectively\n• Cooperate fully with law enforcement when appropriate"
      },
      {
        "title": "To report suspicious activity",
        "text": "Contact our compliance team immediately — we respond within 24 hours"
      }
    ]
  },
  "complaints": {
    "title": "Communication and complaints",
    "description": "Official communication channels, complaints procedures, and time frames",
    "sections": [
      {
        "title": "Communication and complaints policy",
        "text": "Company establishment date: June 29, 2026 | Version: 2.0\n\nAt 4Relief Humanitarian Foundation, we believe that every complaint is an opportunity to improve and build confidence. This policy specifies available communication channels, complaints procedures, time frames for response, and escalation mechanisms.\n\nThis policy complies with the following international standards:\n• GDPR requirements for responding to data subject complaints\n• ISO 10002:2018 standards for customer complaints management\n• European consumer protection law (Directive 2013/11/EU Alternative Dispute Resolution)\n• UK Consumer Rights Act and ADR Rules 2015\n• Turkish Consumer Protection Law No. 6502/2013"
      },
      {
        "title": "Official communication channels",
        "text": "To contact the 4Relief team, use the appropriate channel for your inquiry:\n\n┌───────────────────────────────── ─────────────────────────────────┐\n│ Purpose │ Email │ Duration of response │\n├──────────────────────────┼───── ───────────────────┼─────────────┤\n│ General inquiries │ info@forrelief.org │ 24 hours │\n│ Complaints and concerns │ info@forrelief.org │ 48 hours │\n│ Refund requests │ info@forrelief.org │ 48 hours │\n│ Privacy and data protection │ info@forrelief.org │ 72 hours │\n│ Report fraud │ info@forrelief.org │ 24 hours │\n│ Legal inquiries │ info@forrelief.org │ 5 business days │\n│ Unsubscribe requests │ info@forrelief.org│ 24 hours │\n│ Field Partnerships │ info@forrelief.org │ 5 working days │\n│ Media and Press │ info@forrelief.org │ 48 hours │\n└───────────────────────────────── ─────────────────────────────────┘\n\nAlternative to direct communication:\nContact form on the website: /contact\nAvailable around the clock, a response will arrive within 24 business hours.\n\nOfficial working hours:\nSunday to Thursday: 9 am - 6 pm (Cairo time GMT+2)\nFriday and Saturday: Closed (Monday inbox will be processed)\nEmergencies (fraud and security): 24/7"
      },
      {
        "title": "Types of complaints we handle",
        "text": "We deal with all of the following types of complaints:\n\n1. Financial transaction complaints:\n• Double or false deduction\n• Not receiving the donation receipt\n• Problems in the recovery process\n• Monthly subscription discount after cancellation\n• The difference between the amount offered and the amount discounted\n\n2. Privacy and data complaints:\n• Use of personal data without permission\n• Difficulty exercising GDPR rights (deletion, correction, access)\n• Continue receiving messages after unsubscribing\n• Concerns regarding sharing data with third parties\n\n3. Service quality complaints:\n• Delayed response to inquiries\n• Inaccurate or misleading information on the site\n• Difficulty navigating or using the site\n• Failure to respond to requests for assistance\n\n4. Transparency complaints:\n• Concerns about the use of donated funds\n• Lack of updates about campaigns\n• Lack of clarity in financial reports\n• Doubts about the integrity of any of the organization’s operations\n\n5. Fraud and Security Complaints:\n• Suspicion of fraudulent transactions\n• Alleging impersonation of 4Relief employees\n• Questioning the legitimacy of a particular campaign\n• Report security vulnerabilities on the site"
      },
      {
        "title": "Stages of complaint processing in detail",
        "text": "We follow a clear and time-bound methodology to address each complaint:\n\nThe first stage — receipt and confirmation (within 48 working hours):\n• The complaint is received and recorded in our internal system\n• An automatic receipt confirmation is sent with a unique reference number (#REF-XXXXX)\n• The priority level is determined according to the nature of the complaint (regular / urgent / emergency).\n• A specialized employee is appointed to follow up on the complaint\n\nThe second stage - investigation and collection (within 5 working days):\n• The assigned employee reviews all relevant details\n• Communicates with internal stakeholders (financial, technical, partnerships)\n• Collects the necessary evidence and documents\n• Additional information is requested from the complainant if necessary\n\nPhase Three — Decision and Notification (within two business days of the end of the investigation):\n• The complainant shall be notified of the decision with an explanation of the reasons\n• Actions taken or planned to be taken are mentioned\n• If the request is not completely accepted, the reasons will be clearly stated\n• Escalation options are mentioned if the complainant is not satisfied with the decision\n\nPhase Four - Implementation (according to the agreed upon schedule):\n• Agreed corrective actions are implemented\n• The implementation of the decision is followed up internally\n\nStage 5 — Complaint closure and satisfaction assessment (within 3 days of implementation):\n• A short satisfaction survey is sent to the complainant\n• The complaint and its resolution are recorded in the internal database for learning from it\n• The complaint is included in the periodic quality improvement report"
      },
      {
        "title": "Escalation and appeal mechanisms",
        "text": "If you are not satisfied with the decision:\n\nLevel 1 - Complaints Manager:\n• Contact info@forrelief.org stating your reference number and the reason for your dissatisfaction\n• The file is reviewed by a different manager than the first employee\n• Response time: 5 working days\n\nSecond level - senior management:\n• If the issue is not resolved at the first level, you can request a senior management review\n• Email info@forrelief.org with “Official Escalation” in the subject line\n• Response time: 10 working days\n\nLevel Three - External Parties:\nFor European users:\n• Electronic dispute settlement platform: ec.europa.eu/consumers/odr\n• Local data protection supervisory authority (for privacy complaints)\n\nFor British users:\n• Information Commissioner’s Office (ICO): ico.org.uk (for privacy complaints)\n• Financial Ombudsman Service: for qualified financial complaints\n\nFor Turkish users:\n• Tüketici Hakem Heyeti (Local Consumer Arbitration Board): for financial complaints\n• KVKK Authority: for privacy-related complaints — kvkk.gov.tr\n\nFor users from Arab countries:\n• The consumer protection authority in your relevant country"
      },
      {
        "title": "Rights of the complainant",
        "text": "When you file your complaint, you have the following rights:\n\n• Right to acknowledgment: receive confirmation of receipt of your complaint within 48 hours\n• The right to be informed: Know the name of the employee designated to follow up on your complaint\n• Right to update: receive periodic updates if treatment extends for more than 5 days\n• The right of access: access to the documents and data on which the decision was based\n• The right to object: object to the decision and request its review\n• The right to escalate: escalate the complaint to higher levels or to neutral third parties\n• The right to confidentiality: Confidence that your complaint data is kept confidential and will only be shared for processing purposes\n\nWhat we pledge:\n• We will not treat your complaint with any retaliation\n• We will not reject your complaint without providing a convincing reason\n• We will not charge you any fees to process the complaint\n• We will sincerely apologize if we make a mistake and take effective corrective action"
      },
      {
        "title": "Periodic reports of complaints",
        "text": "Transparency in the performance of the complaints service:\nWe prepare an internal quarterly report that includes:\n• Total complaints received and their classification\n• Average solution time for each type\n• Percentage of complaints resolved satisfactorily\n• Highlight the root causes and improvement measures taken\n• Compared to previous quarters to measure the level of improvement\n\nA summary of this report is available in the Foundation's annual Financial Transparency Report.\n\nDesired goal:\n• Resolving 80% of complaints in the first stage without escalation\n• Achieving 90% or more satisfaction of complainants with the treatment process\n• Maintain an average response time of less than 48 hours for regular complaints"
      },
      {
        "title": "Do you have a complaint or inquiry?",
        "text": "Our team responds within 48 hours and we are committed to resolving your issue"
      }
    ]
  },
  "financial-transparency": {
    "title": "Financial transparency",
    "description": "How FOR RELIEF LTD manages funds: spending allocation, oversight, review and reporting",
    "sections": [
      {
        "title": "Financial transparency policy",
        "text": "Company establishment date: June 29, 2026 | Version: 2.1\n\n4Relief is the name used on this website by FOR RELIEF LTD, a private company limited by shares registered in England and Wales under number 17306194. UK charity registration has not yet been issued.\n\nFOR RELIEF LTD receives funds through the 4Relief website and is responsible for allocating them and managing the stated humanitarian and relief projects. Aid reaches beneficiaries directly through projects implemented by the company or field partners acting on its behalf and under its oversight. Direct delivery of aid does not mean that the entire donation is transferred as cash to each beneficiary; the spending policy explains implementation, processing and operating costs and reserves.\n\nAccounting and disclosure framework:\n• The company prepares its accounts and records under applicable UK company requirements and the accounting framework appropriate to its status.\n• Transparency principles in international standards such as IPSAS may inform our approach where relevant; this is not a claim that IPSAS is the company's adopted accounting framework.\n• European NGO disclosure requirements and Charity Commission rules apply to entities within their scope; references to them do not represent registration or accreditation of this company.\n• Relevant local requirements are considered when projects are implemented through partners in Arab countries and elsewhere.\n• GuideStar and Charity Navigator recommendations are references for improving disclosure, not ratings or certifications held by the company.\n\nOwnership, fees and regional restrictions:\n• The company provides director, representative, ownership and control information as required by its payment provider and official records. It does not claim a charity exemption from ownership disclosure.\n• Processing fees follow the company’s agreement with its payment provider. We do not claim eligibility for discounted charity pricing or that donations are tax-deductible or eligible for Gift Aid.\n• Acceptance of funds and project delivery are subject to applicable laws, sanctions, regional restrictions and payment-provider requirements. Funds are not collected for projects that those requirements do not permit."
      },
      {
        "title": "Financing structure and revenue sources",
        "text": "Expected company funding sources — planning estimates, not actual revenue results:\n\n1. Individual Donations:\nExpected percentage of revenue: 85-90%\n• One-time donations via the website\n• Recurring monthly donations\n• Donations of large amounts from benefactors (Major Donors)\n\n2. Institutional Donations:\nExpected percentage: 5-10%\n• Charitable institutions and endowments\n• Companies within social responsibility programs\n• Family charitable funds\n\n3. Grants & Partnerships:\nExpected percentage: 2-5%\n• Grants from accredited international bodies\n• Partnership programs with humanitarian agencies\n\nFinancing rejection policy:\nWe absolutely reject funding from:\n• Entities included on international sanctions lists\n• Parties whose sources of funds cannot be verified\n• Parties that impose conditions that conflict with our humanitarian principles or restrict our independence\n• Any party associated with illegal or controversial activities"
      },
      {
        "title": "Spend breakdown — every $100 trip",
        "text": "The following is a target planning budget per $100, not a record of actual expenditure or a guaranteed fixed allocation for every project. The target is 85% for direct aid. Reports will identify actual results by project and reporting period; costs may vary with implementation and payment fees:\n\n┌──────────────────────────────── ─────────────────────────────────┐\n│ Item │ Amount │ Percentage │\n├──────────────────────────────── ────┼────────┼──────────────────┤\n│ Direct aid to beneficiaries │ $85 │ 85% │\n│ Of which: food and water │ $34 │ 34% │\n│ Of which: health care and medicines │ $21.25 │ 21.25% │\n│ Of which: shelter and lodging │ $17 │ 17% │\n│ Including: Education and psychological support │ $12.75 │ 12.75% │\n├──────────────────────────────── ────┼────────┼──────────────────┤\n│ Field partners’ costs │ $8 │ 8% │\n│ Including: Logistics and delivery │ $4.80 │ 4.80% │\n│ Among them: documentation and impact reports │ $1.60 │ 1.60% │\n│ Among them: Field supervision │ $1.60 │ 1.60% │\n├──────────────────────────────── ────┼────────┼──────────────────┤\n│ Operational costs │ $4.5 │ 4.5% │\n│ Among them: technology and hosting │ $1.35 │ 1.35% │\n│ Including: Payment processing │ $1.35 │ 1.35% │\n│ Among them: Team │ $1.35 │ 1.35% │\n│ Of which: Legal and Compliance │ $0.45 │ 0.45% │\n├──────────────────────────────── ────┼────────┼──────────────────┤\n│ Transparency and external review │ $1.5 │ 1.5% │\n│ Among them: independent financial audit │ $0.90 │ 0.90% │\n│ Among them: reports and disclosure │ $0.60 │ 0.60% │\n├──────────────────────────────── ────┼────────┼──────────────────┤\n│ Emergency reserve │ $1 │ 1% │\n├──────────────────────────────── ────┼────────┼──────────────────┤\n│ Total │ $100 │ 100% │\n└──────────────────────────────── ─────────────────────────────────┘\n\nOur goal: to gradually raise the proportion of direct aid to 90% by 2027 by improving operational efficiency and increasing the volume of donations."
      },
      {
        "title": "Mechanism for distributing donations to campaigns",
        "text": "Campaign allocation:\nWhen a campaign is selected, the donation after payment processing fees is allocated to that campaign's budget, including aid and its stated implementation costs. This does not mean that 100% is transferred as direct cash assistance to a beneficiary.\n\nFOR RELIEF LTD receives funds through the 4Relief website and is responsible for allocating them and managing the stated humanitarian and relief projects. Aid reaches beneficiaries directly through projects implemented by the company or field partners acting on its behalf and under its oversight. Direct delivery of aid does not mean that the entire donation is transferred as cash to each beneficiary; the spending policy explains implementation, processing and operating costs and reserves.\n\nGeneral donations — planning allocation subject to needs-based review:\n• 50% to the most urgent campaigns based on field assessment\n• 30% to campaigns with the greatest funding gap\n• 20% to an operating reserve for emergency campaigns\nThese are allocation targets, not actual spending results.\n\nPartner disbursements — a planning model adapted in each project agreement:\n• 40% mobilisation payment after contracting and verification\n• 40% progress payment after documenting 50% completion\n• 20% completion payment after verification and the final report\n\nUnspent funds:\n• Donors are notified if a campaign cannot proceed, and options are handled under the refund policy and donation terms.\n• Unspent balances are reviewed regularly, aiming to allocate them within six months where implementation allows, with reasons for any delay explained."
      },
      {
        "title": "Financial audit and independent review",
        "text": "Internal oversight and review:\nThe company's financial oversight plan includes:\n• Monthly review of records and reconciliation of payment gateways and bank accounts\n• Quarterly management summaries comparing spending with budgets\n• Traceable records linking transactions to campaigns and projects\n\nIndependent external review:\n• An external review or annual audit is arranged when legally required or commissioned, according to the scale of activity and available resources.\n• The company does not claim a completed external audit or an auditor's opinion before publishing a dated report supporting that claim.\n• When a review takes place, we aim to publish the disclosable report within 90 days of completion, subject to data protection.\n• Depending on the engagement, the report covers financial position, income and expenditure, cash flows and the reviewer's findings.\n\nInternational transparency recommendations:\nDisclosure principles associated with frameworks such as GuideStar Platinum inform our approach. This reference is not a claim that FOR RELIEF LTD holds GuideStar accreditation or a Platinum rating. Our disclosure plan includes:\n• Public access to available financial reports\n• Explanation of governance policies\n• Identification of directors and responsible officers under applicable requirements\n• Disclosure of the conflict-of-interest policy"
      },
      {
        "title": "Beneficiaries and criteria for selecting partners",
        "text": "The following partner criteria form our intended assessment framework. Their application is documented for each partner and does not represent external accreditation of the company.\n\nCriteria for selecting field partners:\nWe follow a strict methodology for selecting field partners:\n\nMandatory eligibility criteria:\n• ✅ Legal registration in the country of work\n• ✅ At least 3 years of experience in humanitarian work\n• ✅ A clean record free of any violations or investigations\n• ✅ Certified accounting and financial documentation ability\n• ✅ Reliable and trained field team\n• ✅ Commitment to Sphere standards for humanitarian action\n• ✅ Pass the examination of international sanctions lists\n\nPeriodic performance evaluation:\n• Evaluate the performance of each partner after each project\n• Surprise field visits for verification\n• Review documented impact reports\n• A partner who fails the standards is immediately excluded\n\nList of approved partners:\nThe list of current partners is published in the annual transparency report with a summary of the activities of each partner and the amounts disbursed through it."
      },
      {
        "title": "How do you track the impact of your donation?",
        "text": "Donation impact reporting plan:\n\n1. Electronic receipt:\nA receipt is sent after successful payment is confirmed, identifying the transaction, amount, currency, campaign and date. Email delivery may be delayed; a copy can be requested at info@forrelief.org.\n\n2. Campaign updates:\nWe aim for weekly updates on urgent projects and monthly updates on ongoing campaigns, depending on verified information, followed by a final report upon completion.\n\n3. Quarterly impact report:\nWe aim to publish a summary every three months when there is reportable activity, including beneficiary numbers, expenditure, images authorised for publication and comparison with the plan.\n\n4. Annual financial report:\nCompany accounts are prepared to applicable deadlines. We aim to publish an annual summary after the accounts are completed, identifying the reporting period and publication date. This reporting schedule is not evidence of previous reports."
      },
      {
        "title": "View our latest financial reports",
        "text": "Reports are made available when prepared and verified, with their reporting period identified. To request an available report or ask about one in preparation, email info@forrelief.org. Spending plans are not presented as actual financial results."
      }
    ]
  },
  "how-we-use-donations": {
    "title": "How donations are used",
    "description": "The detailed journey of your donation from receipt until it reaches the beneficiary — in steps and numbers",
    "sections": [
      {
        "title": "How are your donations used?",
        "text": "Your donation isn't just a sum of money — it's a life changed, a family eaten, and a child learned. We believe that you have the full right to know the journey of every dollar you donate until it reaches its intended recipients.\n\nObjective of this page:\nExplaining how the platform works in full detail, from the moment you receive your donation until it reaches the final beneficiary, explaining how we ensure efficiency and transparency at every step.\n\nFOR RELIEF LTD receives funds through the 4Relief website and manages their allocation to humanitarian and relief projects. Aid reaches beneficiaries directly through implementation by the company or field partners acting on its behalf and under its oversight. Project budgets include aid and stated implementation costs, as explained in the financial transparency policy."
      },
      {
        "title": "Your donation journey — 7 detailed steps",
        "text": "Step 1 — Complete a secure donation:\nWhen you click Donate, your Stripe or PayPal payment data is processed with SSL/TLS encryption. We don't see or store your card number — it goes directly to the secure payment gateway. You will receive an instant confirmation message with a receipt number.\n\nStep 2 — Receipt and transfer of funds (within 1-3 business days):\nFunds move from the payment gateway to the organization's approved bank account. Each transaction is recorded in an approved accounting system and attributed to the specific campaign.\n\nStep 3 — Customization and Routing (within 24-48 hours):\nIf you donate to a specific campaign, your full amount goes toward that campaign. If you donate publicly, it is distributed according to the field's priority algorithm. Campaign numbers are updated instantly on the website.\n\nStep 4 — Field Partner Verification (Ongoing):\nBefore transferring any amount to a field partner, we check:\n• Validity of his license and field activity\n• His name is free from international sanctions lists\n• Field and logistical readiness to implement the project\n• Signing the detailed implementation contract with the payment schedule\n\nStep 5 — Transfer to the field partner (in batches):\nWe do not transfer the entire amount at once. We follow an achievement-linked payment system:\n• Operation payment (40%): upon signing the contract and fulfilling the readiness conditions\n• Progress Payment (40%): After reliable documentation of 50% completion of the project\n• Completion payment (20%): After complete verification of project completion and submission of the final report\n\nStep 6 — Field Implementation and Documentation:\nThe project partner implements and documents each distribution:\n• Lists of beneficiaries with their names and numbers\n• Documented photos from the field with precise dates and locations\n• Beneficiary certificates and receipts\n• A detailed financial report for each expense\n\nStep 7 — Verification, Report and Notification:\nWe review the partner’s report and verify its accuracy:\n• Matching the numbers of beneficiaries with the plan\n• Verification of financial documents\n• Field visit for verification (in large projects)\nYou'll receive an email with a verified impact report that shows you exactly where your donation went."
      },
      {
        "title": "Humanitarian sectors and how to spend in them",
        "text": "1. Food and water security (34% of direct aid):\n\nClean drinking water:\n• Water distribution points in areas most in need\n• Home water filters (enough for a family of 5 for one year)\n• Water tanks for unserved areas\n• Digging and equipping water wells in remote villages\n\nEmergency food baskets:\n• A basic food basket sufficient for a family of 5 members for two weeks\n• Contents: rice, flour, oil, sugar, canned food (beans, tuna), tea\n• Food baskets for religious seasons (Ramadan, Eid al-Adha)\n• Prepared meals for urgent emergencies\n\n2. Health care (21.25% of direct aid):\n\nEmergency care:\n• First aid and basic medications\n• Equipping field health points\n• Transporting critical patients to hospitals\n\nContinuing care:\n• Medications for chronic diseases (hypertension, diabetes, heart)\n• Maternal and child care\n• Child vaccinations in isolated areas\n• Basic medical equipment for field clinics\n\nMental health:\n• Individual and group psychological support sessions\n• Programs to support children with trauma\n• Psychological support for disaster survivors\n\n3. Accommodation and shelter (17% of direct aid):\n\nEmergency relief:\n• High quality emergency tents (UNHCR Standard)\n• Blankets and covers to protect against the cold\n• Personal hygiene items (soap, sterilizers, towels)\n\nRehabilitation:\n• Building materials to restore damaged homes\n• Help rebuild destroyed rooms\n• Providing electricity to needy families\n\n4. Education (12.75% of direct aid):\n\nSchool support:\n• School bags and educational supplies\n• Standardizing school uniforms for children in need\n• Books and learning supplies\n\nContinuing education:\n• Supporting girls’ education in conservative areas\n• Alternative classrooms in crisis areas\n• University study grants for needy students"
      },
      {
        "title": "What we don't spend on — a clear commitment",
        "text": "In order to ensure the highest percentage of beneficiaries reaches us, we commit not to spend on:\n\n• Paid advertising: We rely on the word of mouth and donor recommendations\n• Luxury offices: We work with low-cost facilities\n• Leisure travel: Any field travel associated with the direct verification requirement\n• Overrated salary: Team salaries are conservative, reasonable and disclosed\n• Promotional events: No expensive parties or shows\n• Costly consulting: We rely on internal efficiency as much as possible\n\nGoal: Reducing operational costs from 15% to less than 10% by 2026."
      },
      {
        "title": "Stories from the field — real impact",
        "text": "These are not just numbers - these are lives changed:\n\nKarima family story:\n“Before the support came, we were drinking unsafe water. The filter we got changed our lives. My children stopped getting sick and went back to school.”\n\nThe story of teacher Somaya:\n“Our school was destroyed. Thanks to building materials and books, 47 children returned to learning. This is not just education — this is hope for a future.”\n\nUmm Fadl’s story:\n“My baby girl was born with the help of the midwife supported by 4Relief. I was very afraid. Today my daughter is healthy and I am grateful to every donor.”\n\nThese true stories come from documented field reports from our partners."
      },
      {
        "title": "Your donation makes a real difference",
        "text": "Join thousands of donors making a difference every day"
      }
    ]
  },
  "privacy": {
    "title": "Privacy Policy",
    "description": "Protect your data in accordance with GDPR and comprehensive international standards",
    "sections": [
      {
        "title": "Privacy Policy and Personal Data Protection",
        "text": "Company establishment date: June 29, 2026 | Version: 3.0\n\nThe 4Relief Humanitarian Foundation holds protecting your privacy of the utmost importance. This policy comprehensively explains how we collect, process, hold and share your personal data, and the full rights you have.\n\nWe comply with the following legal frameworks:\n• European General Data Protection Regulation GDPR (2016/679/EU)\n• UK GDPR / Data Protection Act 2018\n• Turkish Personal Data Protection Law KVKK (No. 6698 of 2016)\n• UAE Personal Data Protection Law PDPL (Decree No. 45 of 2021)\n• Saudi Personal Data Protection System (PDPL) (1443 AH)\n• Egyptian Personal Data Protection Law (No. 151 of 2020)\n• Moroccan Law 09-08 relating to the protection of private persons\n• APEC Framework Principles for Privacy of Personal Information (for Asian countries)\n• Pakistan Privacy Protection Act (PECA 2016 and related regulations)"
      },
      {
        "title": "Who we are — Identity of the data controller",
        "text": "Data Controller data:\nName: 4Relief Humanitarian Foundation\nWebsite: [website link]\nPrivacy email: info@forrelief.org\nData Protection Officer (DPO): info@forrelief.org\n\nData of the main data processors:\n• Stripe Inc. (Card payment processing) — Contact information: stripe.com/privacy\n• PayPal Holdings Inc. (PayPal payment processing) — Contact information: paypal.com/privacy\n• Google LLC (site analytics via Google Analytics) — Contact details: policies.google.com/privacy\n\nData is processed by these processors under binding data processing agreements that ensure compliance with the GDPR and applicable laws."
      },
      {
        "title": "What data we collect and why we collect it",
        "text": "We collect the following types of personal data:\n\nFirst - Identity and contact data:\n┌──────────────────────────────── ────────────────────────────────┐\n│ Data type │ Legal basis │ Source │\n├───────────────────────┼──────── ────────────┼───────────────────┤\n│ Full name │ Contract execution │ User-entered │\n│ Email │ Contract execution │ User-entered │\n│ Phone number (optional) │ Legitimate interest │ User-entered │\n│ Country and region │ Legal obligation │ User-entered │\n└──────────────────────────────── ────────────────────────────────┘\n\nSecond - Financial Transaction Data:\n┌──────────────────────────────── ────────────────────────────────┐\n│ Data type │ Legal basis │ Source │\n├───────────────────────────┼──── ────────────────┼────────────────┤\n│ Donation amount and currency │ Contract execution │ Payment system │\n│ Type and periodicity of donation │ Execution of the contract │ Entered by the user│\n│ Receipt number │ Contract execution │ Our internal system │\n│ Last 4 digits of card │ Transaction security │ Stripe/PayPal │\n│ Transaction status │ Contract execution │ Payment system │\n│ Date and time of donation │ Legal obligation │ Our internal regulations │\n└──────────────────────────────── ────────────────────────────────┘\nIMPORTANT NOTE: We never retain your full card number or CVV. This data is processed directly by Stripe or PayPal and does not pass through our servers.\n\nThird - Technical data (collected automatically):\n• IP address (stored anonymously for security and analysis purposes)\n• Browser type, version and operating system\n• The pages you visited, the order in which they were visited, and the duration of each visit\n• Visit source (search engine, link, social media platform)\n• Device data: screen resolution, browser language, time zone\n• Cookies — See our cookie policy for details\n\nFourth - Contact information:\n• Text of contact form messages\n• Log email correspondence\n• The subject of the inquiry or complaint and its date\n• Data on your complaints and refund requests\n\nFifth - Optional data:\n• Your personal message attached to the donation\n• Preference for anonymous donation\n• Subscribe to the newsletter"
      },
      {
        "title": "The legal basis for each type of processing",
        "text": "In accordance with Article 6 of the GDPR, we process your data based on the following legal bases:\n\n1. Implementation of a contract or agreement (Article 6/1/B):\n   Processing: Completing the donation, issuing the receipt, managing monthly donation subscriptions.\n   Explanation: This processing is necessary to provide the service you have requested.\n\n2. Legal obligation (Article 6/1/c):\n   Processors: Maintain records of financial transactions, comply with AML/CFT requirements, respond to regulatory requests.\n   Explanation: We are required by law to keep these records for specific periods.\n\n3. Legitimate interest (Article 6/1/f):\n   Treatments: improving the site and user experience, fraud prevention, information security.\n   Balancing: We carefully balance our legitimate interests with your fundamental rights.\n   Right to object: You can object to this processing at any time.\n\n4. Approval (Article 6/1/A):\n   Treatments: newsletter, non-essential cookies, optional marketing messages.\n   Right to withdraw: You may withdraw your consent at any time without retroactive effect.\n\nFor users outside the European Union:\nThese legal foundations are equivalent to the requirements set forth in the Turkish KVKK, the UAE PDPL, the Saudi PDPL, and the Egyptian Data Protection Law, and we apply them all."
      },
      {
        "title": "How we use your data in detail",
        "text": "First purpose — providing basic service (mandatory):\n• Process your donation and transfer it to the selected campaign\n• Issuing and sending the electronic receipt immediately\n• Manage and update monthly donation subscriptions\n• Respond to your inquiries and complaints\n• Send updates to the campaign you donated to\n• Providing periodic impact reports\n\nPurpose 2 — Legal Compliance and Security (Mandatory):\n• Compliance with anti-money laundering and terrorist financing laws\n• Fraud detection and investigation\n• Protect the integrity of our platform from unlawful exploitation\n• Responding to requests from approved judicial and regulatory authorities\n• Auditing transactions and documenting their records\n\nThird purpose - improvement and development (legitimate interest):\n• Analyze site statistics to improve performance and experience\n• Develop new features based on usage patterns\n• Fix technical errors\n\nPurpose 4 — Marketing communication (with your consent only):\n• Sending a newsletter with news about the organization and new campaigns\n• Notifications of donation campaigns that may match your interests\n• Messages celebrating humanitarian achievements\nYou can unsubscribe from any message with one click or by emailing us at info@forrelief.org"
      },
      {
        "title": "Sharing data with third parties",
        "text": "Our basic policy: We do not sell, rent, or share your data for commercial purposes.\n\nWe only share your data in the following limited circumstances:\n\n1. Payment service providers:\n   • Stripe Inc.: Receives payment data to process transactions according to PCI-DSS Level 1\n   • PayPal Holdings: Receives order data to complete PayPal transactions\n   • Both are signatories to binding data processing agreements in accordance with the GDPR\n\n2. Analysis tools:\n   • Google Analytics: anonymized usage data (with IP masking enabled)\n   • Does not contain your name or email\n\n3. Email service:\n   • Authorized provider for sending receipts and newsletter\n   • Operates under a binding data processing agreement\n\n4. Field partners:\n   • They receive aggregate data (total donations) only — without any donor identification data\n\n5. Legal and regulatory bodies:\n   • We respond to approved judicial orders and requests from competent regulatory authorities\n   • We report suspicious transactions to the relevant authorities in accordance with AML/CFT requirements\n\n6. International data transfer (for European and UK users):\n   If your data is transferred outside the European Economic Area (EEA) or the United Kingdom:\n   • We apply the European Commission's Standard Contractual Clauses (SCCs).\n   • Or we make sure that the recipient is in a recognized country with an adequate level of protection\n   • You can request a copy of the applicable guarantees via info@forrelief.org"
      },
      {
        "title": "Extended data retention",
        "text": "We retain your data for the following periods of time based on legal and operational requirements:\n\n┌──────────────────────────────── ─────────────────────────────────┐\n│ Data type │ Retention duration │ Reason │\n├───────────────────────────────┼ ─────────────────┼───────────────┤\n│ Financial transaction data │ 7 years │ Tax liability │\n│ KYC and AML records │ 5 years │ FATF requirements │\n│ Contact and correspondence data │ 3 years │ Legal rights │\n│ Technical data and access logs│ 90 days │ Information security │\n│ Newsletter data │ Until cancellation +30 days │ Your wish │\n│ Analytical cookies │ 26 months │ Google max│\n│ KYC │ 5 years │ FATF/AML │\n└──────────────────────────────── ─────────────────────────────────┘\n\nAfter the expiry of the retention periods:\n• Identifiable data: permanently deleted from all systems\n• Non-sensitive data: made anonymous and can be retained for statistical analysis"
      },
      {
        "title": "Your comprehensive legal rights",
        "text": "You have the following full rights regarding your personal data:\n\n┌──────────────────────────────── ────────────────────────────────┐\n│ Right │ Description │ Duration to respond │\n├───────────────────┼─────────── ─────────────────┼──────────────┤\n│ Access and review │ A copy of your saved data │ 30 days │\n│ Correction │ Correction of inaccurate data │ 30 days │\n│ Deletion (forgetting) │ Deletion of your data (with legal restrictions) │ 30 days │\n│ Restriction │ Temporarily stopping the processing of your data │ 30 days │\n│ Portability │ Your data in JSON/CSV format │ 30 days │\n│ Objection │ Objection to certain processing │ Immediate │\n│ Withdrawal of consent │ Withdrawal of any previous consent │ Immediate │\n│ Not subject to an automated decision │ Human review of any automated decision │ 15 days │\n└──────────────────────────────── ────────────────────────────────┘\n\nHow do you exercise your rights?\n• Send your request via email: info@forrelief.org\n• Explain the right you want to exercise and the data involved\n• We may need to verify your identity to protect your data from unauthorized access\n• We respond within 30 days (extendable by 60 days in complex cases with your notice)\n• If we deny your request, we explain the reasons and your rights to appeal\n\nThe right to appeal to the regulatory authorities:\n• European Union: the local data protection supervisory authority\n• United Kingdom: Information Commissioner’s Office ICO — ico.org.uk — Number: 0303 123 1113\n• Türkiye: Personal Data Protection Authority KVKK — kvkk.gov.tr\n• UAE: Telecommunications and Digital Government Regulatory Authority (TDRA) — tdra.gov.ae\n• Saudi Arabia: Personal Data Protection Authority — sdaia.gov.sa\n• Egypt: National Council for Telecommunications Regulation"
      },
      {
        "title": "Data security — technical and organizational measures",
        "text": "Technical Security Measures:\n\nData encryption:\n• SSL/TLS 1.3: Encrypts all data transferred between your device and our servers\n• AES-256: Encrypts sensitive data stored in the database\n• bcrypt: Encrypt passwords using a strong hashing algorithm with random Salt\n\nInfrastructure security:\n• Multi-layer firewalls (WAF + Network Firewall)\n• Intrusion detection and prevention system (IDS/IPS)\n• Regular vulnerability scanning\n• Periodic penetration tests (Penetration Testing)\n\nAccess control:\n• Multi-factor authentication (MFA) is mandatory for administrative access\n• Principle of Least Privilege.\n• Periodic review of access permissions and withdrawal of unsolicited ones\n• Record and track all access to sensitive data\n\nOrganizational Security Measures:\n• A clear and documented information security policy\n• Mandatory training for all employees on data protection\n• Specific procedures for responding to data breach incidents\n• Non-disclosure agreements with all employees and contractors\n\nIn the event of a data breach:\n• We notify regulatory authorities within 72 hours (according to GDPR/UK GDPR)\n• We will notify you personally if the breach poses a high risk to your rights\n• We are taking immediate action to contain the breach and minimize the damage\n• We publish a comprehensive report on the incident and the measures taken"
      },
      {
        "title": "Provisions specific to each jurisdiction",
        "text": "European users (EU GDPR):\n• Our practices meet all GDPR requirements\n• You have the right to file a complaint with the local supervisory authority without prejudice to your other rights\n• Our representative in the European Union: [to be appointed upon future enlargement]\n• Data Protection Officer: info@forrelief.org\n\nBritish users (UK GDPR):\n• We comply with the UK GDPR and the UK Data Protection Act 2018\n• You can complain to the ICO: ico.org.uk\n• Our UK representative: [to be appointed upon expansion]\n\nTurkish Users (KVKK):\n• According to KVKK No. 6698, we commit to full disclosure and rights of access, deletion and correction\n• You can submit a complaint to the KVKK Authority via kvkk.gov.tr\n• Controller data: 4Relief Foundation — info@forrelief.org\n\nEmirati users:\n• We comply with the UAE PDPL Law (Decree No. 45 of 2021)\n• You can contact the TDRA Complaints Authority: tdra.gov.ae\n\nSaudi users:\n• We comply with the Saudi Personal Data Protection System (PDPL).\n• Saudi Data and Artificial Intelligence Authority: sdaia.gov.sa\n\nEgyptian users:\n• We comply with Personal Data Protection Law No. 151 of 2020\n\nMoroccan users:\n• We comply with Law 09-08 on the protection of private persons\n• For complaints: cndp.ma\n\nAsian users:\n• We comply with the APEC Framework Principles for Privacy\n• We respect the provisions of each country's national privacy laws"
      },
      {
        "title": "Questions about your privacy?",
        "text": "Our Data Protection Officer is ready to answer — we respond within 72 hours"
      }
    ]
  },
  "terms": {
    "title": "Terms and Conditions",
    "description": "Terms of use of the platform and obligations of both parties",
    "sections": [
      {
        "title": "General terms and conditions",
        "text": "Company establishment date: June 29, 2026 | Version: 2.0\n\nWelcome to the 4Relief Humanitarian Foundation platform (“Platform” or “Site”). These terms and conditions constitute a binding legal agreement between you and the organization. By using the Site or any of its services, you acknowledge your full agreement to these terms.\n\nIf you do not agree to any of these terms, please stop using the site immediately.\n\nThese terms comply with the following international legislation:\n• European Consumer Protection Directive 2011/83/EU (contracts concluded at a distance)\n• British Electronic Contracts Act (Electronic Commerce Regulations 2002)\n• Turkish E-Commerce Law No. 6563/2014\n• E-commerce systems in Arab countries\n• Electronic Transactions Law for the Gulf Cooperation Council countries"
      },
      {
        "title": "Definition of the parties and scope of the agreement",
        "text": "Website operator and entity responsible for receiving funds: FOR RELIEF LTD, a private company limited by shares registered in England and Wales under number 17306194, trading on this website as 4Relief.\nRegistered office: FOR RELIEF LTD — 71–75 Shelton Street, Covent Garden, London, WC2H 9JQ, United Kingdom.\nEmail: info@forrelief.org\n\nFOR RELIEF LTD receives funds through the 4Relief website and is responsible for allocating them and managing the stated humanitarian and relief projects. Aid reaches beneficiaries directly through projects implemented by the company or field partners acting on its behalf and under its oversight. Direct delivery of aid does not mean that the entire donation is transferred as cash to each beneficiary; the spending policy explains implementation, processing and operating costs and reserves.\n\nParties covered by this agreement:\n\n“The Corporation” / “We” / “Our”:\n4Relief — the website name used by FOR RELIEF LTD for its humanitarian donation platform that aims to support families in need around the world in cooperation with trusted field partners. The platform is developed by WEBEK LTD.\n\n“User” / “You” / “Visitor”:\nAny natural or legal person who accesses the site, browses it, or uses any of its services, regardless of the purpose of use or its geographical location.\n\n\"donor\":\nAny user who makes a single or periodic financial donation through the platform.\n\n\"Services\":\nAll site functions include: donating, viewing campaigns, subscribing to the newsletter, communicating with the team, and using the administrative editor.\n\n\"Content\":\nAll text, images, videos, data, and other materials displayed on the Site.\n\nScope of application:\nThese Terms apply to all uses of the Site regardless of access method (browser, application, API), device used or geographic location."
      },
      {
        "title": "Terms of eligibility for use",
        "text": "To use the site and make donations, the following conditions must be met:\n\n1. Legal age:\n   • 18 years or older in most countries\n   • If your country's laws set a higher age of legal capacity for contracts, these restrictions apply\n   • Individuals under the age of majority: are permitted to donate with the express and supervised written consent of a legal guardian\n\n2. Full legal capacity:\n   • There is no court ruling that limits your eligibility to contract\n   • Not being included on any international sanctions list (OFAC, EU, UN, UK)\n   • You do not reside in a country subject to a comprehensive ban prohibiting international financial transactions\n\n3. Technical requirements:\n   • Have a valid email address\n   • Having a valid electronic payment method (credit card/PayPal)\n   • An Internet connection that provides access to our servers\n\n4. Approval of policies:\n   • View and agree to the privacy policy\n   • View the donations and refund policy\n   • View the anti-money laundering and fraud policy"
      },
      {
        "title": "The nature of the relationship between the institution and the donor",
        "text": "Enterprise Business Model - What are we?\n\nOur role as a humanitarian mediator:\nWe work as a bridge between donors and crisis areas through reliable field partners. We are not party to a direct relationship with the ultimate beneficiaries.\n\nWhat we offer:\n• A secure technical platform to accept digital donations\n• Manage and direct donations to specific campaigns\n• Supervising field partners and measuring impact\n• Issuing receipts and transparent financial reports\n\nWhat we don't offer:\n• Guarantees on specific results of field projects\n• Tax or legal advice\n• Ensuring tax acceptance of your donations in your country (varies according to the laws of each country)\n• Direct access to final beneficiaries\n\nNature of donation:\nDonating through our platform is not the purchase of a service or commodity — it is a voluntary humanitarian giving. The donation does not entail any contractual obligations for a certain amount of field results."
      },
      {
        "title": "Permitted and prohibited use of the site",
        "text": "Permitted uses:\n• Browse website content and campaigns\n• Donate for genuine humanitarian purposes\n• Subscribe to the newsletter\n• Communicate with our team\n• Share website content (links) on social media\n\nStrictly prohibited uses:\nCriminal and financial:\n• ❌ Using the website to launder money or finance terrorist activities\n• ❌ Making donations using stolen or hacked payment methods\n• ❌ Creating fake accounts for fraudulent purposes\n• ❌ Donating on behalf of parties subject to international sanctions\n\nTechnology and security:\n• ❌ Attempting to hack the site, its servers or databases\n• ❌ Injecting malicious code or malware\n• ❌ Conduct DDoS or other operational attacks\n• ❌ Using data extraction tools (scraping/crawling) without permission\n• ❌ Trying to test the limits of the financial system (Card Testing)\n\nIntellectual property and content:\n• ❌ Copy or republish website content without permission\n• ❌ Pretending to have an official affiliation with the institution\n• ❌ Create websites that imitate the official website\n\nViolation of any of these prohibitions may entail:\n• Stop access to the site immediately\n• Reporting to the competent legal and security authorities\n• Claim compensation for the resulting damages"
      },
      {
        "title": "Donor Responsibilities — Representations and Warranties",
        "text": "By completing any donation process, you represent and warrant to the Foundation:\n\n1. Legitimacy of the financial source:\n   • Donated funds are acquired through legitimate, legal means\n   • The funds are not linked to any criminal or prohibited activity\n   • You are not listed on any international sanctions or terrorism list\n\n2. Correctness of information:\n   • All data you provided (name, email, payment information) is true, accurate and up to date\n   • Your data will be updated immediately in the event of any change affecting your subscriptions\n\n3. Authority and authorization:\n   • You are legally authorized to use the payment method used\n   • Your donation is made of your own free will, without any coercion or deception\n   • Do not donate on behalf of any third party without clear legal authorization\n\n4. Understanding and acceptance:\n   • You understand that donations are humanitarian and do not create any commercial or proprietary rights\n   • Understand the unpredictable nature of humanitarian work\n   • I agreed to the Terms of Service and Privacy Policy before donating"
      },
      {
        "title": "The Foundation's obligations towards donors",
        "text": "We are committed to providing service according to the following standards:\n\n1. Processing donations:\n   • Every donation is processed in real time via a secure payment gateway\n   • Send an electronic receipt within one minute of completing the donation\n   • Allocate your donation after payment fees to the selected campaign budget, including aid and stated implementation costs\n   • Continuously updating campaign numbers in real time\n\n2. Complete transparency:\n   • Publish detailed quarterly financial reports\n   • Publish periodic field impact reports supported by pictures and figures\n   • Full disclosure of the identity of field partners and their selection criteria\n\n3. Quality of service:\n   • Respond to your inquiries within 24 working hours\n   • Providing a clear and fair refund policy\n   • Treating complaints seriously within specific periods of time\n\n4. Data protection:\n   • Protect your personal data according to the highest security standards\n   • Do not share your data for commercial purposes\n   • Notifying you of any security breach within 72 hours\n\n5. Continuity:\n   • Work to ensure the site is available at the highest possible rate\n   • Advance announcement of any planned maintenance\n   • Providing alternative donation channels in emergency situations"
      },
      {
        "title": "Intellectual property and content",
        "text": "Ownership of the platform and code:\nThe platform is fully developed by WEBEK LTD (webek.org) and all intellectual property rights to the code are reserved to WEBEK LTD (webek.org). For full details, see the Copyrights and Licenses page.\n\nContent ownership:\n• Original text, images and designs on the site: joint property of the Foundation and its developer\n• Campaign content: ownership of the organization, with the donor retaining the right to his or her personal information\n\nLicense to use for visitors:\nWe grant Visitors a limited, non-exclusive, non-transferable license to:\n• View the content for personal, non-commercial purposes\n• Share website links\n\nNo license is granted to:\n• Copy or republish the content\n• Use of logo or trademark\n• Build platforms inspired by this site"
      },
      {
        "title": "Limitations and Disclaimers",
        "text": "1. Disclaimer of field results:\nThe Foundation is a humanitarian intermediary. We do not guarantee that specific results will be achieved from field projects given the complexity of humanitarian work and changing field conditions.\n\n2. Technical interruption disclaimer:\nWe do not guarantee that the Site will be available 24/7 without any interruption. The website may be temporarily suspended for maintenance or due to technical malfunctions beyond our control.\n\n3. Disclaimer of external websites:\nThe Site may contain links to external websites. We do not accept any responsibility for the content, practices or privacy policies of such sites.\n\n4. Consultation Disclaimer:\nContent on our site is for informational purposes only and is not legal, tax or financial advice.\n\n5. Limits of compensation:\nIf our legal liability is proven, compensation is limited to the amount of the donation made or $100, whichever is greater, unless the laws of your country provide otherwise.\n\n6. Force Majeure:\nWe are not responsible for any failure or delay resulting from: natural disasters, armed conflicts, epidemics, government decisions, global network outages, or any event beyond our reasonable control."
      },
      {
        "title": "Dispute resolution mechanism and applicable law",
        "text": "Progressive approach to conflict resolution:\n\nThe first stage - amicable solution (duration: 14 working days):\nSend your detailed complaint to info@forrelief.org with dates, amounts and documents. We are committed to responding and negotiating in good faith within 14 business days.\n\nPhase 2 - Mediation (duration: 30 days):\nIf an amicable solution fails, the dispute shall be referred to a neutral mediator chosen by mutual agreement. Mediation costs will be borne equally unless otherwise agreed.\n\nThe third stage - arbitration or adjudication:\nFor European users:\n• Right to resort to the ODR platform: ec.europa.eu/consumers/odr\n• Or to the competent courts in your country of residence\n\nFor British users:\n• The right to resort to approved ADR bodies\n• Or to the competent British courts\n\nFor Turkish users:\n• Tüketici Hakem Heyeti for financial disputes\n• Or Turkish commercial courts\n\nFor Arab and Asian users:\n• The competent courts in the country of residence\n\nConsumer protection rights:\nThese Terms do not limit any mandatory rights granted under your country's consumer protection laws. If the laws of your country give you broader rights, those rights apply."
      },
      {
        "title": "Modification of Terms and Prior Notice",
        "text": "Right of amendment:\nWe reserve the right to modify these Terms for legitimate reasons such as: changing applicable laws, developing the Services, or improving clarity.\n\nNotice procedures:\n• Material changes: We will provide email notice 30 days prior to effectiveness\n• Minor changes (linguistic or formatting): Published immediately with updated “Last Updated” date\n• We always publish a clear summary of the changes made\n\nApproval of amendments:\nYour continued use of the site after the amendments become effective constitutes implicit acceptance of them.\nIf you do not agree to the amendments, you have the right to:\n• Stop your monthly subscription before the amendment takes effect\n• Request deletion of your data\n• Refrain from using the site"
      },
      {
        "title": "Have a legal question?",
        "text": "Our legal team responds to your inquiries within 48 hours"
      }
    ]
  },
  "refund-policy": {
    "title": "Donations and refunds policy",
    "description": "Cases eligible for refund and their detailed procedures",
    "sections": [
      {
        "title": "Donations and refunds policy",
        "text": "Company establishment date: June 29, 2026 | Version: 2.0\n\nWe believe in the donor's right to fully understand the donation and refund policy before making the decision to donate. This policy is formulated with the utmost clarity and transparency and complies with international consumer protection regulations.\n\nLegal frameworks to which this policy complies:\n• European Consumer Protection Directive 2011/83/EU (contracts concluded at a distance)\n• British Consumer Rights Act 2015 (Consumer Rights Act)\n• Turkish Consumer Protection Law No. 6502/2013\n• Saudi consumer protection system\n• UAE Consumer Protection Law (Decree No. 15 of 2020)\n• Consumer protection laws in other Arab countries\n• APEC Framework Principles for Consumer Protection"
      },
      {
        "title": "Nature of Donations — The difference between a donation and a purchase",
        "text": "Donating is fundamentally different from purchasing a good or service:\n\nDonate:\n• A free, voluntary donation for humanitarian purposes\n• Does not create a title or claim to specific services\n• Addressed directly to beneficiaries to whom you are not personally related\n\nPurchase:\n• A commercial transaction that results in a right to obtain a specific good/service\n• Generally refundable according to consumer laws\n\nBasic policy:\nDue to the humanitarian nature of donations and the immediate channeling of funds to field projects, fully processed donations are not refundable as a general rule.\n\nProtected exceptions:\nHowever, we are committed to providing a refund in the exceptional cases detailed in this policy, and in all cases where mandatory laws in your country require a refund."
      },
      {
        "title": "Cases in which a refund is granted",
        "text": "Case 1 - Documented technical errors (highest priority):\nRequires immediate full refund:\n• The amount was deducted more than once due to a reliable technical error (two transactions appeared instead of one)\n• Deducting an amount different from the amount you clearly agreed to\n• Complete debit from your bank account when the transaction failed in our system (you did not receive a confirmation)\n• A technical error in identifying the beneficiary campaign, such that your donation was directed to a campaign other than the one you chose\n\nAction: We issue the refund as soon as we verify the error without any diligence or delay.\n\nCase 2 — Documented Fraud (Full Refund):\n• Using your card or account without your permission and proving this with an official report from the bank or police\n• There is an official report issued by your financial institution confirming the fraudulent activity\n• Notify the site that your email account has been hacked and donations have been made without your knowledge\n\nAction: Full refund + full cooperation with the bank and law enforcement.\n\nThird case — campaign cancellation (full refund or transfer):\n• If the campaign to which you donated is canceled before any field implementation begins\n• We will inform you immediately of your choices: a full refund or a transfer to the campaign of your choice\n\nProcedure: Full refund or transfer as desired within 7 days.\n\nCase 4 - Error in amount (immediate request):\n• If you made a mistake in entering an amount much larger than intended and contact us within one hour\n• We examine each case individually — if the funds have not yet been transferred to the field partner, we may refund the difference\n\nAction: Contact us immediately at info@forrelief.org stating the intended amount and the actual amount.\n\nCase Five - Exceptional Humanitarian Circumstances:\n• A documented financial emergency (illness, death, disaster) occurring within 24 hours of the donation\n• There is reasonable evidence of unexpected financial distress\n\nProcedure: We examine each case with compassion and fairness — donations to ongoing projects may not be refundable.\n\nAdditional rights under the laws of some countries:\nFor European and British users: The “right of withdrawal” law may give you 14 days to review electronic transactions, although the nature of humanitarian donations differs from commercial contracts. If you think this right applies to your situation, write to us and we will consider it seriously."
      },
      {
        "title": "Cases in which a refund is not granted",
        "text": "We believe in complete clarity, as these cases do not require recovery:\n\n• Change of opinion 7 days after donation without a qualifying reason\n• Dissatisfaction with the frequency of updates received from the campaign\n• Dissatisfaction with field reports despite their accuracy and reliability\n• Feeling remorseful about donating without an objective reason\n• Wanting to transfer the amount to another campaign (but we can make a new donation)\n• The donation period expires without the campaign completing its objectives (the funds are directed to similar campaigns)\n• Payment gateway processing fees originally charged (Stripe/PayPal)\n• Donations that have already been directed to the field partner and have begun to be implemented"
      },
      {
        "title": "Recurring Monthly Donations — Cancellation and Refunds",
        "text": "Right of cancellation:\nCancellation is an absolute and unconditional right. You may cancel your monthly subscription at any time for any or no reason.\n\nHow to cancel:\n• Email: info@forrelief.org\n• Cancellation request: Send the cancellation request to info@forrelief.org from the email address used for the donation, with the receipt number.\n• You can also request cancellation via info@forrelief.org\n\nEffective period of cancellation:\n• Cancellation will take effect immediately upon confirmation\n• No amount will be deducted in the next month’s cycle\n• You will receive a cancellation confirmation message within one hour\n\nRefunds of payments made before cancellation:\n• As a general rule, payments for previous months are not refundable\n• Critical exception: If an amount is deducted after the confirmed cancellation date, it will be refunded immediately and in full with an official apology\n\nSubscription suspension:\nIf you are experiencing temporary financial difficulty:\n• You can request to suspend the subscription for 1-3 months\n• The subscription returns automatically after the end of the suspension period\n• Email us at info@forrelief.org\n\nChange the monthly amount:\n• You can reduce or increase the subscription amount at any time\n• The change will take effect from the following month's cycle"
      },
      {
        "title": "Procedures for submitting a refund request",
        "text": "Step 1 — Apply (within 7 days of donation):\nSend an email to: info@forrelief.org\n\nThe letter must include:\n• Message subject: “Refund Request — [Receipt Number]”\n• Your full name as entered when donating\n• The email used when donating\n• Donation date, amount and currency\n• Electronic receipt number\n• The reason for requesting a refund in detail\n• Any supporting documentation (screenshot, account statement, fraud report)\n\nStep 2 — Confirm receipt (within 48 business hours):\n• Automated confirmation message with reference number (#REF-XXXXX)\n• Appoint a specialized employee to review your application\n\nStep 3 — Review and Verification (within 5 business days):\n• We verify the transaction details in our system\n• We will contact you if we need additional information\n• We review the status of funds being channeled to the field partner\n\nStep 4 — Decision and Notification (within 2 days of completion of review):\n• We will notify you of the decision explaining the reason for approval or rejection\n• In the event of rejection, we will explain the method of objection\n\nStep 5 — Refund Processing (After Approval):\n• Stripe: 5-10 business days (depends on bank and country)\n• PayPal: 3-7 business days\n• The original payment gateway processing fee (1.5-3%) may be deducted in cases not caused by a technical error\n\nStep 6 — Confirm receipt:\n• We send a confirmation message that the recovery has been completed\n• If you do not receive the amount within the specified period, contact us immediately"
      },
      {
        "title": "Recovery priority table",
        "text": "Refund requests are processed according to the following priority levels:\n\nHighest priority (response within 24 business hours):\n• Double deduction or documented technical error\n• Fraud documented with official data\n• Discount after confirmation of subscription cancellation\n\nHigh priority (reply within 48 business hours):\n• Canceling a campaign before implementation\n• Error in the amount (immediate submission within an hour)\n• Documented emergency circumstances\n\nRegular priority (response within 5 business days):\n• Other cases that require detailed review\n• Requests that require verification from the field partner\n\nNote: If you are a European or British donor and consider that the right of “Cooling-off Period” applies to your case, indicate this explicitly in your application and we will give you priority."
      },
      {
        "title": "Have a refund request?",
        "text": "Our team responds within 48 business hours — we are committed to resolving your claim fairly"
      }
    ]
  }
};
